Implement workflow for setting recipe version
TileDB-Inc/tiledb-vector-search-feedstock pull request #21
Opened 2024-01-03 14:57 UTC by dudoslav

2024-01-04 14:31 UTC, jdblischak requested changes

2024-01-04 14:31 UTC, jdblischak commented on .github/workflows/release.yml
> +          sed -i "s/version = \".*\"/version = \"$VERSION\"/g" recipe/meta.yaml
You'll also need to ensure that the `build_number` is reset to `0` when auto-bumping the version

2024-01-04 16:08 UTC, jdblischak commented
In case it could be useful, here is some code I use to edit conda recipes.

The quickest option is to use `sed`. I like this approach for its simplicity, but it's also caused me problems when the file has been edited, and the patterns no longer match. Here's the [code](https://github.com/TileDB-Inc/conda-forge-nightly-controller/blob/51519a0f8340b32cf737fcb59b76c6a91c42dc47/scripts/tiledb/update-recipe.sh#L21) for bumping the build number:

```sh
# Ensure build number is 0
sed -i \
  s/"  number: [0-9]\+"/"  number: 0"/ \
  recipe/meta.yaml
```

A more robust option is to parse the recipe with ruamel.yaml, but this requires Python.  The payoff is that the [code](https://github.com/TileDB-Inc/conda-forge-nightly-controller/blob/main/scripts/tiledb-py/update-recipe.py) is much more robust and easier to read.

2024-01-08 10:09 UTC, dudoslav commented
I am currently investigating if we could rework https://github.com/dudoslav/cf-scripts in order to create PRs for our repos so this PR is inactive for few days.

2024-01-22 10:27 UTC, dudoslav commented
Closing this PR since this should be implemented by conda forge autobot

2024-01-22 10:27 UTC, closed without merging