Increment TileDB-Vector-Search version to 0.0.20
TileDB-Inc/tiledb-vector-search-feedstock pull request #24
Opened 2024-01-10 12:16 UTC by dudoslav

Increment version of TileDB-Vector-Search to 0.0.20.

This PR still needs to wait until TileDB-Vector-Search is actually updated to this new version.

2024-01-10 12:17 UTC, dudoslav commented
Also re-render might be in place

2024-01-12 16:31 UTC, jdblischak commented
I found the problem! The commit to build TileDB-Py 0.25.0 with tiledb 2.19 failed only for the win-64 py39 job!

![image](https://github.com/TileDB-Inc/tiledb-vector-search-feedstock/assets/1608317/f66419d0-05d6-46a0-b0a7-d58a1a366687)

https://github.com/conda-forge/tiledb-py-feedstock/commit/4ff96c1c149e6cea6b456dd10f6b188941e3437e

2024-01-12 16:46 UTC, jdblischak commented
And for a post-mortem, the strange solver error about the outdated lz4-c is because the solver was choosing a super old version of tiledb-py to install. I don't know why it is choosing this one, but the actual problem was that none was suitable.

I discovered this by installing an env on Windows using the specs I posted above. Then in that env I tried to install `tiledb=2.19`. The lz4-c 1.8.1 was in an attempt to install tiledb-py 0.3.1. Also note that the results are slightly confusing since it says that tiledb-py 0.25.0 needs to be installed with tiledb 2.18, but that is just an artifact of https://github.com/conda-forge/tiledb-py-feedstock/pull/191#issuecomment-1885658469, which we are in the process of cleaning up.


```sh
mamba env create --file vector-search.yaml
conda activate vector-search
mamba install --dry-run tiledb=2.19
## │  ├─ tiledb-py 0.3.1 would require
## │  │  └─ tiledb 1.4.* , which requires
## │  │     └─ lz4-c >=1.8.1.2,<1.8.2.0a0 , which requires
## │  │        └─ vc 14 , which does not exist (perhaps a missing channel);
## └─ tiledb 2.19**  is not installable because it conflicts with any installable versions previously reported.
mamba install --dry-run tiledb=2.19 tiledb-py=0.25
## Could not solve for environment specs
## The following packages are incompatible
## ├─ tiledb-py 0.25**  is installable with the potential options
## │  ├─ tiledb-py 0.25.0 would require
## │  │  └─ tiledb >=2.18.3,<2.19.0a0 , which can be installed;
## │  ├─ tiledb-py 0.25.0 would require
## │  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
## │  ├─ tiledb-py 0.25.0 would require
## │  │  └─ python >=3.11,<3.12.0a0 , which can be installed;
## │  └─ tiledb-py 0.25.0 would require
## │     └─ python >=3.8,<3.9.0a0 , which can be installed;
## └─ tiledb 2.19**  is not installable because it conflicts with any installable versions previously reported.
```

2024-01-12 17:45 UTC, jdblischak requested changes

2024-01-12 17:45 UTC, jdblischak commented on recipe/meta.yaml
> +    - lz4-c 1.9.4 # [win and py==39]
You can remove this now

2024-01-12 17:45 UTC, jdblischak commented on recipe/meta.yaml
> +    - lz4-c 1.9.4 # [win and py==39]
and this

2024-01-12 21:12 UTC, dudoslav commented on recipe/meta.yaml
> +    - lz4-c 1.9.4 # [win and py==39]
done

2024-01-12 21:12 UTC, dudoslav commented on recipe/meta.yaml
> +    - lz4-c 1.9.4 # [win and py==39]
done

2024-01-12 21:12 UTC, jdblischak approved these changes

2024-01-13 11:57 UTC, merged