Do not package tiledb.so
TileDB-Inc/tiledb-vector-search-feedstock pull request #35
Opened 2024-05-06 09:09 UTC by dudoslav

2024-05-06 11:00 UTC, dudoslav commented
When running locally (`build-locally.py` with `--verbose` in pip install) I can see that the found `libtiledb.so` is in conda environment:
```
-- The C compiler identification is GNU 12.3.0
  -- The CXX compiler identification is GNU 12.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /home/conda/feedstock_root/build_artifacts/tiledb-vector-search_1714992933502/_build_env/bin/x86_64-conda-linux-gnu-cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /home/conda/feedstock_root/build_artifacts/tiledb-vector-search_1714992933502/_build_env/bin/x86_64-conda-linux-gnu-c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Starting TileDB-Vectorsearch superbuild.
  -- Found TileDB: /home/conda/feedstock_root/build_artifacts/tiledb-vector-search_1714992933502/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libtiledb.so.2.22
  -- Not found clang-tidy
  -- Not found clang-format
  -- Configuring done (0.3s)
  -- Generating done (0.0s)
  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_FIND_ROOT_PATH_MODE_LIBRARY
      CMAKE_INSTALL_LIBDIR


  -- Build files have been written to: /tmp/tmpn5gv_34p/build
  2024-05-06 10:57:45,319 - scikit_build_core - WARNING - Unsupported CMAKE_ARGS ignored: -DCMAKE_BUILD_TYPE=Release
  2024-05-06 10:57:45,319 - scikit_build_core - WARNING - Unsupported CMAKE_ARGS ignored: -DCMAKE_INSTALL_PREFIX=/home/conda/feedstock_root/build_artifacts/tiledb-vector-search_1714992933502/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
  *** Building project with Unix Makefiles...
```

2024-05-06 11:23 UTC, dudoslav commented
Hm, but it seems that `libtiledb.so` is still present:
```
(base) taco:linux-64 dudoslav$ tar -xvf pkg-tiledb-vector-search-0.1.0-py310ha8360b7_0.tar.zst
...
lib/python3.10/site-packages/tiledb/vector_search/include/mdspan/mdspan.hpp
lib/python3.10/site-packages/tiledb/vector_search/lib64/cmake/docopt/docopt-config.cmake
lib/python3.10/site-packages/tiledb/vector_search/lib/libtiledb.so.2.20 << HERE
lib/python3.10/site-packages/tiledb/vector_search/embeddings/random_embedding.py
lib/python3.10/site-packages/tiledb/vector_search/include/experimental/mdarray
lib/python3.10/site-packages/tiledb/vector_search/include/experimental/__p0009_bits/extents.hpp
lib/python3.10/site-packages/tiledb/vector_search/lib64/cmake/docopt/docopt-targets-release.cmake
lib/python3.10/site-packages/tiledb/vector_search/object_readers/__pycache__/bioimage_reader.cpython-310.pyc
lib/python3.10/site-packages/tiledb_vector_search-0.1.0.dist-info/entry_points.txt
lib/python3.10/site-packages/tiledb/vector_search/embeddings/soma_geneptw_embedding.py
```

2024-06-05 14:35 UTC, jdblischak requested changes
Please rebase onto main to get the latest changes. In PR #37, I added the flags `--no-build-isolation` (so that `pip` builds with the dependencies installed in the conda host/build env) and `-v` (so that we can see the CMake logs).

2024-06-05 14:35 UTC, jdblischak commented on recipe/meta.yaml
> +  script: TileDB_DIR=${PREFIX} {{ PYTHON }} -m pip install --no-deps --ignore-installed .
```suggestion
  script: TILEDB_PATH=${PREFIX} {{ PYTHON }} -m pip install --no-deps --ignore-installed .
```

From our discussion in https://github.com/TileDB-Inc/TileDB-Vector-Search/pull/361, I believe this should now be `TILEDB_PATH=${PREFIX}`

2024-06-06 10:11 UTC, closed without merging